config/routes.rb
Rails.application.routes.draw do
  get 'cv/show'
  get 'cv/suitable_for_vacancy'
  get 'vacancy/show'
  get 'vacancy/suitable_for_cv'

  get '/cvs', to: 'cv#index', as: :cvs
  get '/vacancies', to: 'vacancy#index', as: :vacancies


  get 'cv/new', to: 'cv#new', as: :new_cv
  post 'cv/new', to: 'cv#create', as: :create_cv
  get 'vacancy/new', to: 'vacancy#new', as: :new_vacancy
  post 'vacancy/new', to: 'vacancy#create', as: :create_vacancy

  root to: 'main#index'
end

app/models/cv.rb
class Cv < ActiveRecord::Base
  validates :full_name, presence: true, format: {with: /[а-яА-Я]+\s+[а-яА-Я]+\s+[а-яА-Я]+/}
  validates :contacts, presence: true, format: {
      with: /(8|\+7)?([ .-]?)\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})|(\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z)/i
  }
  validates :salary, numericality: {greater_than_or_equal_to: 0}
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates :full_name, presence: true, format: {with: /[а-яА-Я]+\s+[а-яА-Я]+\s+[а-яА-Я]+/}
  validates :contacts, presence: true, format: {
      with: /(8|\+7)?([ .-]?)\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})|(\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z)/i
  }
  validates :salary, numericality: {greater_than_or_equal_to: 0}
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  before_save :default_values

  def default_values
    self.expiration_date ||= 1.month.from_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cv_controller.rb
class CvController < ApplicationController
  def new
    @cv = Cv.new
  end

  def index
    @cvs = Cv.all.page params[:page]
  end

  def show
    @cv = Cv.find params[:id]
  end

  def suitable_for_vacancy id
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/vacancy_controller.rb
class VacancyController < ApplicationController
  def new
    @vacancy = Vacancy.new
  end

  def create
    @vacancy = Vacancy.new vacancy_params
  end

  def index
    @cvs = Vacancy.all.page params[:page]
  end

  def show
    @cv = Vacancy.find params[:id]
  end

  def suitable_for_cv id
  end

  private
  def vacancy_params
    params.require(:vacancy).permit :name, :expiration_date, :salary, :contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cv_helper.rb
module CvHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/vacancy_helper.rb
module VacancyHelper
end

app/views/cv/_form.html.haml
.form
  = semantic_nested_form_for @cv, html: {class: 'form-horizontal' } do |f|
    .form-group
      = f.label :full_name
      = f.text_field :full_name, class: 'form-control'
    .form-group
      = f.label :salary
      = f.text_field :salary, class: 'form-control'
    .form-group
      = f.label :contacts
      = f.text_area :contacts, class: 'form-control'
    .form-group
      = f.input :status, class: 'checkbox'
    = f.submit t('save'), class: 'btn btn-default'

app/views/cv/index.html.haml
%table.table.table-striped
  %thead
    %tr
      %th= t('.full_name')
      %th= t('.contacts')
      %th= t('.status')
      %th= t('.salary')
  -@cvs.each do |cv|
    %tr
      %td= cv.full_name
      %td= cv.contacts
      %td= cv.status
      %td= number_to_currency(cv.salary, locale: :ru)
= paginate @cvs

app/views/cv/show.html.haml
%h1 Cv#show
%p Find me in app/views/cv/show.html.haml

app/views/cv/suitable_for_vacancy.html.haml
%h1 Cv#suitable_for_vacancy
%p Find me in app/views/cv/suitable_for_vacancy.html.haml

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "EmploymentAgency"
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all"
    = favicon_link_tag 'favicon.ico', rel: 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"

  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-brand= link_to t('.employment_agency'), root_path
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to t('.vacancies'), vacancies_path
            %li= link_to t('.cvs'), cvs_path

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
      %footer
        %p= t('.footer_text').html_safe

app/views/main/index.html.haml
= link_to t('.add_cv'), new_cv_path
= link_to t('.add_vacancy'), new_vacancy_path

app/views/vacancy/_form.html.haml
.form
  = nested_form_for @vacancy, html: {class: 'form-horizontal' } do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :salary
      = f.text_field :salary, class: 'form-control'
    .form-group
      = f.label :contacts
      = f.text_area :contacts, class: 'form-control'
    .form-group
      = f.label :expiration_date
      = f.date_field :expiration_date, class: 'form-control'
    = f.submit t('save'), class: 'btn btn-default'

app/views/vacancy/index.html.haml
%h1 Vacancy#index
%p Find me in app/views/vacancy/index.html.haml

app/views/vacancy/new.html.haml
= render 'form'

app/views/vacancy/show.html.haml
%h1 Vacancy#show
%p Find me in app/views/vacancy/show.html.haml

app/views/vacancy/suitable_for_cv.html.haml
%h1 Vacancy#suitable_for_cv
%p Find me in app/views/vacancy/suitable_for_cv.html.haml